# -*- coding: utf-8 -*-
"""fut_prec_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AKwmEfTgcTTTH0BK-ypoEhbppxYLIhdk
"""

from google.colab import drive

drive.mount('/content/drive')

import xarray as xr
import pandas as pd
import numpy as np
import glob

PISCOsns_grid = xr.open_dataset("/content/drive/MyDrive/Google_Colab_temp/others/SNS/grid_SW.nc")
PISCOsns_grid

hydro_time = pd.date_range("2036-01-01", "2065-12-31", freq="D")
hydro_time = hydro_time[~((hydro_time.day == 29) & (hydro_time.month == 2))]

nc_files = glob.glob("/content/drive/MyDrive/MOD_CC_SENAMHI_DAY/SENAMHI_pp_*_rcp85_scal.nc")

encoding = {v: {'zlib': True, 'complevel': 5} for v in ["p"]}

nc_files_data = []
for nc_file in nc_files:
    piscop = xr.open_dataset(nc_file)
    piscop = piscop.rename({"lat": "latitude", "lon": "longitude", "pr": "p"})
    piscop = piscop.sel(time=slice("2035-09-01", "2065-08-31"))
    piscop = piscop.isel(time=~piscop.time.dt.strftime('%m-%d').isin("02-29"))
    piscop["time"] = hydro_time
    piscop_anual = piscop.resample(time="1Y").sum().mean(dim="time")  # 30 years
    piscop_anual = piscop_anual.reindex(longitude=PISCOsns_grid.longitude.values,
                                        latitude=PISCOsns_grid.latitude.values,
                                        method="nearest")
    piscop_anual.to_netcdf("/content/drive/MyDrive/Google_Colab_temp/others/SNS/p_" + nc_file.split("/")[-1],
                           encoding=encoding, engine='netcdf4')